services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  celery:
    build: .
    # ← point into the sub-folder where manage.py & provet/ live
    working_dir: /app/provet
    command: celery -A provet.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=provet.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  web:
    build: .
    # ← same here
    working_dir: /app/provet
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=provet.settings
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

volumes:
  postgres_data:
